echo "#!/usr/bin/env bash" > "config.local.sh"
echo "#AWS configuration" >> "config.local.sh"
echo "export AWS_ACCESS_KEY_ID=" >> "config.local.sh"
echo "export AWS_SECRET_ACCESS_KEY=" >> "config.local.sh"
echo "" >> "config.local.sh"
echo "#BNET configuration" >> "config.local.sh"
echo "export BNET_CLIENT_ID=" >> "config.local.sh"
echo "export BNET_CLIENT_SECRET=" >> "config.local.sh"
echo "export BNET_AUTHORIZE_URI=" >> "config.local.sh"
echo "export BNET_TOKEN_URI=" >> "config.local.sh"
