apiVersion: skaffold/v1
kind: Config
metadata:
  name: wow-ah-scraper
build:
  artifacts:
  - image: localhost:32000/ui
    context: ui
    sync:
      infer:
      - '**/*.js'
      - '**/*.vue'

deploy:
  kubeContext: microk8s
  kubectl:
    manifests:
    - k8s/**/*.yaml
